"""
Lookup tables for F1 25 telemetry enum values.
"""

TEAM_IDS = {
    0: 'Mercedes',
    1: 'Ferrari',
    2: 'Red Bull Racing',
    3: 'Williams',
    4: 'Aston Martin',
    5: 'Alpine',
    6: 'RB',
    7: 'Haas',
    8: 'McLaren',
    9: 'Sauber',
    255: 'No Team',
}

DRIVER_IDS = {
    0: 'Carlos Sainz',
    1: 'Daniil Kvyat',
    2: 'Daniel Ricciardo',
    3: 'Fernando Alonso',
    4: 'Felipe Massa',
    6: 'Kimi Raikkonen',
    7: 'Lewis Hamilton',
    9: 'Max Verstappen',
    10: 'Nico Hulkenberg',
    11: 'Kevin Magnussen',
    12: 'Romain Grosjean',
    13: 'Sebastian Vettel',
    14: 'Sergio Perez',
    15: 'Valtteri Bottas',
    17: 'Esteban Ocon',
    19: 'Lance Stroll',
    20: 'Arron Barnes',
    21: 'Martin Giles',
    22: 'Alex Murray',
    23: 'Lucas Roth',
    24: 'Igor Correia',
    25: 'Sophie Levasseur',
    26: 'Jonas Schiffer',
    27: 'Alain Forest',
    28: 'Jay Letourneau',
    29: 'Esto Saari',
    30: 'Yasar Atiyeh',
    31: 'Callisto Calabresi',
    32: 'Naota Izum',
    33: 'Howard Clarke',
    34: 'Wilheim Kaufmann',
    35: 'Marie Laursen',
    36: 'Flavio Nieves',
    37: 'Peter Belousov',
    38: 'Klimek Michalski',
    39: 'Santiago Moreno',
    40: 'Benjamin Coppens',
    41: 'Noah Visser',
    42: 'Gert Waldmuller',
    43: 'Julian Quesada',
    44: 'Daniel Jones',
    45: 'Artem Markelov',
    46: 'Tadasuke Makino',
    47: 'Sean Gelael',
    48: 'Nyck De Vries',
    49: 'Jack Aitken',
    50: 'George Russell',
    51: 'Maximilian Gunther',
    52: 'Nirei Fukuzumi',
    53: 'Luca Ghiotto',
    54: 'Lando Norris',
    55: 'Sergio Sette Camara',
    56: 'Louis Deletraz',
    57: 'Antonio Fuoco',
    58: 'Charles Leclerc',
    59: 'Pierre Gasly',
    62: 'Alexander Albon',
    63: 'Nicholas Latifi',
    64: 'Dorian Boccolacci',
    65: 'Niko Kari',
    66: 'Roberto Merhi',
    67: 'Arjun Maini',
    68: 'Alessio Lorandi',
    69: 'Ruben Meijer',
    70: 'Rashid Nair',
    71: 'Jack Tremblay',
    74: 'Antonio Giovinazzi',
    75: 'Robert Kubica',
    78: 'Nobuharu Matsushita',
    79: 'Nikita Mazepin',
    80: 'Guanya Zhou',
    81: 'Mick Schumacher',
    82: 'Callum Ilott',
    83: 'Juan Manuel Correa',
    84: 'Jordan King',
    85: 'Mahaveer Raghunathan',
    86: 'Tatiana Calderon',
    87: 'Anthoine Hubert',
    88: 'Guiliano Alesi',
    89: 'Ralph Boschung',
    255: 'Human Player',
}

TRACK_IDS = {
    0: 'Melbourne',
    1: 'Paul Ricard',
    2: 'Shanghai',
    3: 'Sakhir (Bahrain)',
    4: 'Catalunya',
    5: 'Monaco',
    6: 'Montreal',
    7: 'Silverstone',
    8: 'Hockenheim',
    9: 'Hungaroring',
    10: 'Spa',
    11: 'Monza',
    12: 'Singapore',
    13: 'Suzuka',
    14: 'Abu Dhabi',
    15: 'Texas',
    16: 'Brazil',
    17: 'Austria',
    18: 'Sochi',
    19: 'Mexico',
    20: 'Baku (Azerbaijan)',
    21: 'Sakhir Short',
    22: 'Silverstone Short',
    23: 'Texas Short',
    24: 'Suzuka Short',
    25: 'Hanoi',
    26: 'Zandvoort',
    27: 'Imola',
    28: 'Portimao',
    29: 'Jeddah',
    30: 'Miami',
    31: 'Las Vegas',
    32: 'Losail',
}

SESSION_TYPES = {
    0: 'Unknown',
    1: 'P1',
    2: 'P2',
    3: 'P3',
    4: 'Short P',
    5: 'Q1',
    6: 'Q2',
    7: 'Q3',
    8: 'Short Q',
    9: 'OSQ',
    10: 'R',
    11: 'R2',
    12: 'R3',
    13: 'Time Trial',
}

WEATHER = {
    0: 'Clear',
    1: 'Light Cloud',
    2: 'Overcast',
    3: 'Light Rain',
    4: 'Heavy Rain',
    5: 'Storm',
}

TYRE_COMPOUND_ACTUAL = {
    7: 'Inter',
    8: 'Wet',
    9: 'Dry (Classic)',
    10: 'Wet (Classic)',
    11: 'Super Soft (F2)',
    12: 'Soft (F2)',
    13: 'Medium (F2)',
    14: 'Hard (F2)',
    15: 'Wet (F2)',
    16: 'C5',
    17: 'C4',
    18: 'C3',
    19: 'C2',
    20: 'C1',
    21: 'C0',
    22: 'C6',
}

TYRE_COMPOUND_VISUAL = {
    7: 'Inter',
    8: 'Wet',
    16: 'Soft',
    17: 'Medium',
    18: 'Hard',
    19: 'Super Soft (F2)',
    20: 'Soft (F2)',
    21: 'Medium (F2)',
    22: 'Hard (F2)',
}

SURFACE_TYPES = {
    0: 'Tarmac',
    1: 'Rumble Strip',
    2: 'Concrete',
    3: 'Rock',
    4: 'Gravel',
    5: 'Mud',
    6: 'Sand',
    7: 'Grass',
    8: 'Water',
    9: 'Cobblestone',
    10: 'Metal',
    11: 'Ridged',
}

DRIVER_STATUS = {
    0: 'In Garage',
    1: 'Flying Lap',
    2: 'In Lap',
    3: 'Out Lap',
    4: 'On Track',
}

RESULT_STATUS = {
    0: 'Invalid',
    1: 'Inactive',
    2: 'Active',
    3: 'Finished',
    4: 'Did Not Finish',
    5: 'Disqualified',
    6: 'Not Classified',
    7: 'Retired',
}

PENALTY_TYPES = {
    0: 'Drive Through',
    1: 'Stop Go',
    2: 'Grid Penalty',
    3: 'Penalty Reminder',
    4: 'Time Penalty',
    5: 'Warning',
    6: 'Disqualified',
    7: 'Removed From Formation Lap',
    8: 'Parked Too Long Timer',
    9: 'Tyre Regulations',
    10: 'This Lap Invalidated',
    11: 'This And Next Lap Invalidated',
    12: 'This Lap Invalidated Without Reason',
    13: 'This And Next Lap Invalidated Without Reason',
    14: 'This And Previous Lap Invalidated',
    15: 'This And Previous Lap Invalidated Without Reason',
    16: 'Retired',
    17: 'Black Flag Timer',
}

ERS_DEPLOY_MODE = {
    0: 'None',
    1: 'Medium',
    2: 'Hotlap',
    3: 'Overtake',
}

INFRINGEMENT_TYPES = {
    0: 'Blocking By Slow Driving',
    1: 'Blocking By Wrong Way Driving',
    2: 'Reversing Off The Start Line',
    3: 'Big Collision',
    4: 'Small Collision',
    5: 'Collision Failed To Hand Back Position Single',
    6: 'Collision Failed To Hand Back Position Pair',
    7: 'Corner Cutting Gained Time',
    8: 'Corner Cutting Overtake Single',
    9: 'Corner Cutting Overtake Pair',
    10: 'Crossed Pit Exit Lane',
    11: 'Ignoring Blue Flags',
    12: 'Ignoring Yellow Flags',
    13: 'Ignoring Drive Through',
    14: 'Too Many Drive Throughs',
    15: 'Drive Through Reminder Serve Within N Laps',
    16: 'Drive Through Reminder Serve This Lap',
    17: 'Pit Lane Speeding',
    18: 'Parked For Too Long',
    19: 'Ignoring Tyre Regulations',
    20: 'Too Many Penalties',
    21: 'Multiple Warnings',
    22: 'Approaching Disqualification',
    23: 'Tyre Regulations Select Single',
    24: 'Tyre Regulations Select Multiple',
    25: 'Lap Invalidated Corner Cutting',
    26: 'Lap Invalidated Running Wide',
    27: 'Corner Cutting Ran Wide Gained Time Minor',
    28: 'Corner Cutting Ran Wide Gained Time Significant',
    29: 'Corner Cutting Ran Wide Gained Time Extreme',
    30: 'Lap Invalidated Wall Riding',
    31: 'Lap Invalidated Flashback Used',
    32: 'Lap Invalidated Reset To Track',
    33: 'Blocking The Pitlane',
    34: 'Jump Start',
    35: 'Safety Car To Car Collision',
    36: 'Safety Car Illegal Overtake',
    37: 'Safety Car Exceeding Allowed Pace',
    38: 'Virtual Safety Car Exceeding Allowed Pace',
    39: 'Formation Lap Below Allowed Speed',
    40: 'Formation Lap Parking',
    41: 'Retired Mechanical Failure',
    42: 'Retired Terminally Damaged',
    43: 'Safety Car Falling Too Far Back',
    44: 'Black Flag Timer',
    45: 'Unserved Stop Go Penalty',
    46: 'Unserved Drive Through Penalty',
    47: 'Engine Component Change',
    48: 'Gearbox Change',
    49: 'Parc Ferme Change',
    50: 'League Grid Penalty',
    51: 'Retry Penalty',
    52: 'Illegal Time Gain',
    53: 'Mandatory Pitstop',
    54: 'Attribute Assigned',
}

NATIONALITY = {
    1: 'American',
    2: 'Argentinean',
    3: 'Australian',
    4: 'Austrian',
    5: 'Azerbaijani',
    6: 'Bahraini',
    7: 'Belgian',
    8: 'Bolivian',
    9: 'Brazilian',
    10: 'British',
    11: 'Bulgarian',
    12: 'Cameroonian',
    13: 'Canadian',
    14: 'Chilean',
    15: 'Chinese',
    16: 'Colombian',
    17: 'Costa Rican',
    18: 'Croatian',
    19: 'Cypriot',
    20: 'Czech',
    21: 'Danish',
    22: 'Dutch',
    23: 'Ecuadorian',
    24: 'English',
    25: 'Emirian',
    26: 'Estonian',
    27: 'Finnish',
    28: 'French',
    29: 'German',
    30: 'Ghanaian',
    31: 'Greek',
    32: 'Guatemalan',
    33: 'Honduran',
    34: 'Hong Konger',
    35: 'Hungarian',
    36: 'Icelander',
    37: 'Indian',
    38: 'Indonesian',
    39: 'Irish',
    40: 'Israeli',
    41: 'Italian',
    42: 'Jamaican',
    43: 'Japanese',
    44: 'Jordanian',
    45: 'Kuwaiti',
    46: 'Latvian',
    47: 'Lebanese',
    48: 'Lithuanian',
    49: 'Luxembourger',
    50: 'Malaysian',
    51: 'Maltese',
    52: 'Mexican',
    53: 'Monegasque',
    54: 'New Zealander',
    55: 'Nicaraguan',
    56: 'Northern Irish',
    57: 'Norwegian',
    58: 'Omani',
    59: 'Pakistani',
    60: 'Panamanian',
    61: 'Paraguayan',
    62: 'Peruvian',
    63: 'Polish',
    64: 'Portuguese',
    65: 'Qatari',
    66: 'Romanian',
    67: 'Russian',
    68: 'Salvadoran',
    69: 'Saudi',
    70: 'Scottish',
    71: 'Serbian',
    72: 'Singaporean',
    73: 'Slovakian',
    74: 'Slovenian',
    75: 'South Korean',
    76: 'South African',
    77: 'Spanish',
    78: 'Swedish',
    79: 'Swiss',
    80: 'Thai',
    81: 'Turkish',
    82: 'Uruguayan',
    83: 'Ukrainian',
    84: 'Venezuelan',
    85: 'Barbadian',
    86: 'Welsh',
    87: 'Vietnamese',
}

FORMULA = {
    0: 'F1 Modern',
    1: 'F1 Classic',
    2: 'F2',
    3: 'F1 Generic',
    4: 'Beta',
    6: 'Esports',
    8: 'F1 World',
    9: 'F1 Elimination',
}

GAME_MODE = {
    0: 'Event Mode',
    3: 'Grand Prix',
    4: 'Grand Prix 23',
    5: 'Time Trial',
    6: 'Splitscreen',
    7: 'Online Custom',
    8: 'Online League',
    11: 'Career Invitational',
    12: 'Championship Invitational',
    13: 'Championship',
    14: 'Online Championship',
    15: 'Online Weekly Event',
    17: 'Story Mode',
    19: 'Career 22',
    20: 'Career 22 Online',
    21: 'Career 23',
    22: 'Career 23 Online',
    127: 'Benchmark',
}

RULE_SET = {
    0: 'Practice & Qualifying',
    1: 'Race',
    2: 'Time Trial',
    4: 'Time Attack',
    6: 'Checkpoint Challenge',
    8: 'Autocross',
    9: 'Drift',
    10: 'Average Speed Zone',
    11: 'Rival Duel',
}

SAFETY_CAR_STATUS = {
    0: 'No Safety Car',
    1: 'Full Safety Car',
    2: 'Virtual Safety Car',
    3: 'Formation Lap',
}

PIT_STATUS = {
    0: 'None',
    1: 'Pitting',
    2: 'In Pit Area',
}

EVENT_CODES = {
    b'SSTA': 'Session Started',
    b'SEND': 'Session Ended',
    b'FTLP': 'Fastest Lap',
    b'RTMT': 'Retirement',
    b'DRSE': 'DRS Enabled',
    b'DRSD': 'DRS Disabled',
    b'TMPT': 'Team Mate In Pits',
    b'CHQF': 'Chequered Flag',
    b'RCWN': 'Race Winner',
    b'PENA': 'Penalty Issued',
    b'SPTP': 'Speed Trap Triggered',
    b'STLG': 'Start Lights',
    b'LGOT': 'Lights Out',
    b'DTSV': 'Drive Through Served',
    b'SGSV': 'Stop Go Served',
    b'FLBK': 'Flashback',
    b'BUTN': 'Button Status',
    b'RDFL': 'Red Flag',
    b'OVTK': 'Overtake',
    b'SCAR': 'Safety Car',
    b'COLL': 'Collision',
}
